const API_BASE = '';
let currentUser = null, allClassmates = [], allTeachers = [];
function escapeHtml(s) { if (!s) return ''; return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;'); }
function tr(s, n) { return s && s.length > n ? s.substring(0, n) + '...' : (s||''); }

const ROLE_CONFIG = {
  student: { tabs: [{ id: 'photos', icon: '📷', label: '相册' },{ id: 'classmates', icon: '🎓', label: '同学录' },{ id: 'teachers', icon: '👨‍🏫', label: '老师' },{ id: 'signature', icon: '✍️', label: '签名墙' },{ id: 'myMessages', icon: '💬', label: '留言' },{ id: 'songs', icon: '🎵', label: '歌单' },{ id: 'profile', icon: '👤', label: '我的' }] },
  teacher: { tabs: [{ id: 'photos', icon: '📷', label: '相册' },{ id: 'evaluate', icon: '📝', label: '评价学生' },{ id: 'myMessages', icon: '💬', label: '留言' },{ id: 'thanks', icon: '🙏', label: '感谢' },{ id: 'signature', icon: '✍️', label: '签名墙' },{ id: 'songs', icon: '🎵', label: '歌单' },{ id: 'profile', icon: '👤', label: '我的' }] },
  admin: { tabs: [{ id: 'photos', icon: '📷', label: '相册' },{ id: 'messages', icon: '💬', label: '留言' },{ id: 'users', icon: '👥', label: '人物' },{ id: 'feedbacks', icon: '📊', label: '评价' },{ id: 'signature', icon: '✍️', label: '签名墙' },{ id: 'songs', icon: '🎵', label: '歌单' },{ id: 'console', icon: '💻', label: '控制台' },{ id: 'editor', icon: '📝', label: '源码' },{ id: 'profile', icon: '👤', label: '我的' }] }
};

let audio = null, lyricsData = [], currentLyricIndex = -1, currentSongName = '';
function initMusicPlayer() {
  audio = new Audio('/干杯.mp3'); currentSongName = '干杯';
  fetch('/干杯.lrc').then(r => { if (!r.ok) throw new Error('No lyrics'); return r.text(); }).then(t => parseLRC(t)).catch(() => { document.getElementById('lyricsContent').innerHTML = '<div style="color:var(--gray-4);padding:20px;">暂无歌词</div>'; });
  audio.addEventListener('timeupdate', updateProgress);
  audio.addEventListener('loadedmetadata', () => { document.getElementById('duration').textContent = formatTime(audio.duration); });
  audio.addEventListener('play', () => { document.querySelector('#playBtn svg').innerHTML = '<path d="M6 19h4V5H6v14zm8-14v14h4V5h-4z"/>'; document.getElementById('musicToggle').classList.add('playing'); });
  audio.addEventListener('pause', () => { document.querySelector('#playBtn svg').innerHTML = '<path d="M8 5v14l11-7z"/>'; document.getElementById('musicToggle').classList.remove('playing'); });
  audio.addEventListener('ended', () => { playNextSong(); });
}
function parseLRC(t) { const ls = t.split('\n'); lyricsData = []; ls.forEach(l => { const m = l.match(/\[(\d{2}):(\d{2})\.(\d{2,3})\]/); if (m) { const tm = parseInt(m[1])*60+parseInt(m[2])+parseInt(m[3])/1000; const c = l.replace(/\[.*?\]/g,'').trim(); if (c) lyricsData.push({ time: tm, content: c }); } }); lyricsData.sort((a,b) => a.time-b.time); const ct = document.getElementById('lyricsContent'); ct.innerHTML = lyricsData.length ? lyricsData.map((l,i) => `<div class="lyric-line" data-index="${i}">${escapeHtml(l.content)}</div>`).join('') : '<div style="color:var(--gray-4);padding:20px;">暂无歌词</div>'; }
function updateProgress() { if (!audio) return; const p = (audio.currentTime/audio.duration)*100||0; document.getElementById('progressBar').style.width = p+'%'; document.getElementById('currentTime').textContent = formatTime(audio.currentTime); let ni = -1; for (let i=0;i<lyricsData.length;i++) { if (audio.currentTime>=lyricsData[i].time) ni=i; } if (ni!==currentLyricIndex) { document.querySelectorAll('.lyric-line').forEach(l=>l.classList.remove('active')); const a=document.querySelector(`.lyric-line[data-index="${ni}"]`); if(a){a.classList.add('active');a.scrollIntoView({block:'center',behavior:'smooth'});} currentLyricIndex=ni; } }
function formatTime(s) { if (isNaN(s)) return '0:00'; return `${Math.floor(s/60)}:${Math.floor(s%60).toString().padStart(2,'0')}`; }
function togglePlay() { if (!audio) initMusicPlayer(); audio?.paused ? audio.play() : audio?.pause(); }
function seekTo(e) { if (!audio) return; const r = e.currentTarget.getBoundingClientRect(); audio.currentTime = ((e.clientX-r.left)/r.width)*audio.duration; }
function toggleMusic() { const p = document.getElementById('musicPanel'); if (p.classList.contains('show')) p.classList.remove('show'); else { if (!audio) initMusicPlayer(); p.classList.add('show'); } }
function togglePanel() { document.getElementById('musicPanel').classList.remove('show'); }
async function playNextSong() { try { const s = await (await fetch('/songs')).json(); if (!s.length) { document.getElementById('musicToggle').classList.remove('playing'); return; } const ci = s.findIndex(x => x.name===currentSongName); playSong(s[(ci+1)%s.length].filename, s[(ci+1)%s.length].name); } catch(e) { document.getElementById('musicToggle').classList.remove('playing'); } }

async function uploadFilesToGitHub(files, folder, subfolder='') {
  const fd = new FormData();
  for (const f of files) fd.append('files', f);
  fd.append('folder', folder);
  if (subfolder) fd.append('subfolder', subfolder);
  return await (await fetch('/upload-file', { method: 'POST', body: fd })).json();
}

async function loadClassmatesList() { try { window.allNames = (await (await fetch('/classmates-list')).json()).map(d=>d.name); } catch(e){} }
async function loadClassmates() { try { allClassmates = await (await fetch('/classmates')).json(); } catch(e){} }
async function loadTeachers() { try { allTeachers = await (await fetch('/teachers')).json(); } catch(e){} }

function showNameList() { const m=document.getElementById('nameListModal'),o=document.getElementById('nameListOptions'); o.innerHTML = (window.allNames&&window.allNames.length)?window.allNames.map(n=>`<div class="name-option" onclick="selectName('${escapeHtml(n)}')">${escapeHtml(n)}</div>`).join(''):'<div class="empty-state">暂无数据</div>'; m.style.display='flex'; }
function hideNameList() { document.getElementById('nameListModal').style.display='none'; }
function selectName(n) { document.getElementById('nameInput').value=n; hideNameList(); }

async function login() {
  const name=document.getElementById('nameInput').value.trim(),pw=document.getElementById('passwordInput').value,err=document.getElementById('loginError');
  if(!name||!pw){err.textContent='请输入姓名和密码';return;}
  try { const r=await fetch('/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,password:pw})}); const d=await r.json(); if(d.success){currentUser=d.user;localStorage.setItem('currentUser',JSON.stringify(currentUser));showMainPage();}else{err.textContent=d.error;} } catch(e){err.textContent='网络错误';}
}
document.addEventListener('DOMContentLoaded',()=>{ const pw=document.getElementById('passwordInput'),nm=document.getElementById('nameInput'); if(pw)pw.addEventListener('keydown',e=>{if(e.key==='Enter')login();}); if(nm)nm.addEventListener('keydown',e=>{if(e.key==='Enter')login();}); });

function showMainPage() { document.getElementById('loginPage').classList.remove('active');document.getElementById('mainPage').classList.add('active'); const cfg=ROLE_CONFIG[currentUser.role]||ROLE_CONFIG.student; document.getElementById('userBadge').textContent=currentUser.role==='admin'?'👑 管理员':(currentUser.role==='teacher'?'👨‍🏫 老师':'🎓 同学'); renderTabBar(cfg.tabs);switchTab(cfg.tabs[0].id);loadClassmates();loadTeachers(); }
function renderTabBar(tabs) { const bar=document.getElementById('tabBar'); bar.innerHTML=tabs.map(t=>`<button class="tab-item" data-tab="${t.id}"><span class="tab-icon">${t.icon}</span><span>${t.label}</span></button>`).join(''); bar.querySelectorAll('.tab-item').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab))); }
function switchTab(tid) {
  document.querySelectorAll('.tab-item').forEach(t=>t.classList.remove('active')); document.querySelector(`[data-tab="${tid}"]`)?.classList.add('active');
  const ts={photos:'相册',teachers:'老师',classmates:'同学录',evaluate:'评价学生',thanks:'感谢',messages:'所有留言',users:'所有人物',profile:'我的',myMessages:'我的留言',feedbacks:'评价/感谢',signature:'签名墙',songs:'歌单',console:'控制台',editor:'源码编辑'};
  document.getElementById('pageTitle').textContent=ts[tid]||tid; document.getElementById('contentArea').innerHTML='<div class="empty-state">加载中...</div>';
  setTimeout(()=>{const fn={photos:renderPhotos,teachers:renderTeachers,classmates:renderClassmates,myMessages:renderMyMessages,evaluate:renderEvaluate,thanks:renderThanks,messages:renderAllMessages,users:renderAllUsers,feedbacks:renderAllFeedbacks,signature:renderSignature,songs:renderSongs,console:renderConsole,editor:renderEditor,profile:renderProfile};if(fn[tid])fn[tid]();},10);
}

// ========== 同学详情弹窗 ==========
async function openClassmateDetail(name) {
  try {
    const contact=await(await fetch(`/contact/${encodeURIComponent(name)}`)).json();
    const msgsToMe=await(await fetch(`/messages/${encodeURIComponent(name)}`)).json();
    const msgsFromMe=await(await fetch(`/messages-from/${encodeURIComponent(currentUser.name)}`)).json();
    const msgsToName=msgsFromMe.filter(m=>m.to_name===name);
    const av=contact.avatar||'🎓',em=av.length<=2||!av.startsWith('http');
    let h=`<div style="text-align:center;margin-bottom:16px;"><div class="avatar-large" style="border-radius:12px;">${em?av:`<img src="${escapeHtml(av)}" class="avatar-img">`}</div><h3>${escapeHtml(name)}</h3></div>`;
    if(contact.intro) h+=`<div class="card-detail" style="margin-bottom:12px;text-align:center;">📝 ${escapeHtml(contact.intro)}</div>`;
    if(contact.motto) h+=`<div class="card-detail" style="margin-bottom:12px;text-align:center;font-style:italic;">💬 "${escapeHtml(contact.motto)}"</div>`;
    if(contact.phone||contact.email||contact.wechat||contact.qq){ h+='<div class="card-detail" style="margin-bottom:12px;">'; if(contact.phone)h+=`<div class="contact-line"><span>📱</span>${escapeHtml(contact.phone)}</div>`; if(contact.qq)h+=`<div class="contact-line"><span>🐧</span>${escapeHtml(contact.qq)}</div>`; if(contact.wechat)h+=`<div class="contact-line"><span>💬</span>${escapeHtml(contact.wechat)}</div>`; if(contact.email)h+=`<div class="contact-line"><span>📧</span>${escapeHtml(contact.email)}</div>`; h+='</div>'; }
    h+='<h4 style="margin-top:16px;">TA给我的留言</h4>'; const ft=msgsToMe.filter(m=>m.from_name===name);
    if(!ft.length)h+='<div class="empty-state" style="padding:20px;">暂无</div>'; else ft.forEach(m=>{h+=`<div class="memory-card"><div class="memory-header"><span class="memory-from">${escapeHtml(m.from_name)}</span><span class="memory-time">${new Date(m.created_at).toLocaleString()}</span></div><div class="memory-content">${escapeHtml(m.content)}</div></div>`;});
    h+='<h4 style="margin-top:16px;">我给TA的留言</h4>'; if(!msgsToName.length)h+='<div class="empty-state" style="padding:20px;">暂无</div>'; else msgsToName.forEach(m=>{h+=`<div class="memory-card"><div class="memory-header"><span class="memory-from">我</span><span class="memory-time">${new Date(m.created_at).toLocaleString()}</span></div><div class="memory-content">${escapeHtml(m.content)}</div></div>`;});
    document.getElementById('modalTitle').textContent=`查看 ${name}`; document.getElementById('modalBody').innerHTML=h;
    document.getElementById('modalFooter').innerHTML=`<button class="btn btn-secondary" onclick="closeModal()">关闭</button><button class="btn btn-primary" onclick="closeModal();openMessageModal('${escapeHtml(name)}')">留言</button>`;
    document.getElementById('modal').classList.add('show');
  }catch(e){alert('加载失败');}
}

// ========== 我的留言 ==========
async function renderMyMessages() { const c=document.getElementById('contentArea'); try { const ms=await(await fetch(`/messages/${encodeURIComponent(currentUser.name)}`)).json(); if(!ms||!ms.length){c.innerHTML='<div class="empty-state"><div class="empty-icon">💬</div>还没有人给你留言</div>';return;} c.innerHTML='<h4 style="margin-bottom:16px;">💭 别人对我说的话</h4>'+ms.map(m=>`<div class="memory-card"><div class="memory-header"><span class="memory-from">${escapeHtml(m.from_name)}</span><span class="memory-time">${new Date(m.created_at).toLocaleString()}</span></div><div class="memory-content">${escapeHtml(m.content)}</div></div>`).join(''); }catch(e){c.innerHTML='<div class="empty-state">加载失败</div>';} }

// ========== 相册 ==========
async function renderPhotos() { const c=document.getElementById('contentArea'); try { const ps=await(await fetch('/photos')).json(); let h='<div class="upload-btn" onclick="openUploadModal()"><span>📷</span> 上传照片</div><div class="photo-grid">'; if(!ps||!ps.length){h+='<div class="empty-state" style="grid-column:1/-1;">还没有照片</div>';}else{ps.forEach(p=>{const del=currentUser.role==='admin'||p.uploaded_by===currentUser.name;h+=`<div class="photo-item"><img src="${escapeHtml(p.image_url)}" loading="lazy" onclick="viewPhoto('${escapeHtml(p.image_url)}','${escapeHtml(p.title)}')" onerror="this.style.background='var(--gray-2)'">${del?`<button class="photo-delete-btn" onclick="event.stopPropagation();deletePhoto(${p.id})">🗑️</button>`:''}</div>`;});} c.innerHTML=h+'</div>'; }catch(e){c.innerHTML='<div class="empty-state">加载失败</div>';} }
function openUploadModal() { document.getElementById('modalTitle').textContent='上传照片'; document.getElementById('modalBody').innerHTML='<div class="form-group"><label class="form-label">选择照片（可多选）</label><input type="file" id="photoFiles" class="input" accept="image/*" multiple></div><div id="photoProgress" style="display:none;"><div class="progress-bar-bg"><div class="progress-bar-fill" id="photoProgressFill"></div></div><p id="photoProgressText" style="text-align:center;font-size:13px;color:var(--gray-4);margin-top:8px;">上传中...</p></div>'; document.getElementById('modalFooter').innerHTML='<button class="btn btn-secondary" onclick="closeModal()">取消</button><button class="btn btn-primary" id="photoUploadBtn" onclick="doUploadPhoto()">上传</button>'; document.getElementById('modal').classList.add('show'); }
async function doUploadPhoto() {
  const files = document.getElementById('photoFiles').files;
  if (!files || files.length === 0) { alert('请选择照片'); return; }
  document.getElementById('photoProgress').style.display = 'block';
  document.getElementById('photoUploadBtn').disabled = true;
  const now = new Date();
  const ts = `${now.getFullYear()}${(now.getMonth()+1).toString().padStart(2,'0')}${now.getDate().toString().padStart(2,'0')}_${now.getHours().toString().padStart(2,'0')}${now.getMinutes().toString().padStart(2,'0')}${now.getSeconds().toString().padStart(2,'0')}`;
  const renamedFiles = [];
  for (let i = 0; i < files.length; i++) {
    const f = files[i];
    const ext = f.name.includes('.') ? f.name.split('.').pop() : 'jpg';
    const newName = `${ts}_${i+1}.${ext}`;
    renamedFiles.push(new File([f], newName, { type: f.type }));
  }
  try {
    const r = await uploadFilesToGitHub(renamedFiles, 'photos');
    if (r.results) {
      let success = 0;
      for (let i = 0; i < r.results.length; i++) {
        if (r.results[i].success) {
          const rawUrl = `/${r.results[i].path}`;
          await fetch('/photos', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ uploaded_by: currentUser.name, title: renamedFiles[i].name, description: '', image_url: rawUrl }) });
          success++;
        }
      }
      document.getElementById('photoProgressFill').style.width = '100%';
      document.getElementById('photoProgressText').textContent = `完成 ${success}/${files.length}`;
      setTimeout(() => { closeModal(); renderPhotos(); }, 1000);
    } else { alert('上传失败'); document.getElementById('photoUploadBtn').disabled = false; }
  } catch (e) { alert('上传失败'); document.getElementById('photoUploadBtn').disabled = false; }
  document.getElementById('photoProgress').style.display = 'none';
}
function viewPhoto(url, title) { document.getElementById('modalTitle').textContent=title; document.getElementById('modalBody').innerHTML=`<img src="${escapeHtml(url)}" style="width:100%;border-radius:12px;">`; document.getElementById('modalFooter').innerHTML='<button class="btn btn-primary" onclick="closeModal()">关闭</button>'; document.getElementById('modal').classList.add('show'); }
async function deletePhoto(id){if(!confirm('确定删除？'))return;try{await fetch(`/photos/${id}`,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({requester:currentUser.name})});renderPhotos();}catch(e){alert('删除失败');}}

// ========== 老师 ==========
async function renderTeachers(){const c=document.getElementById('contentArea');try{const ts=await(await fetch('/teachers')).json();if(!ts||!ts.length){c.innerHTML='<div class="empty-state"><div class="empty-icon">👨‍🏫</div>暂无老师</div>';return;}let h='<div class="global-search-box"><input type="text" id="teacherSearch" class="input" placeholder="搜索老师...（请等全加载完后再搜索否则会有BUG）" onkeyup="filterList(\'teacher\')"></div><div id="teachersListContainer"></div>';c.innerHTML=h;const ct=document.getElementById('teachersListContainer');const sm={'语文':'📖','数学':'📐','英语':'🌍','物理':'⚡','化学':'🧪','政治':'🏛️','历史':'📜','音乐':'🎵','体育':'⚽','美术':'🎨'};for(const t of ts){const contact=await(await fetch(`/contact/${encodeURIComponent(t.name)}`)).json();const card=document.createElement('div');card.className='person-card searchable-item';card.dataset.name=t.name;card.dataset.searchText=(t.name+' '+t.subject+' '+(contact.phone||'')+' '+(contact.qq||'')+' '+(contact.wechat||'')).toLowerCase();let ci='';if(contact.phone)ci+=`<div class="contact-line"><span>📱</span>${tr(escapeHtml(contact.phone),15)}</div>`;if(contact.qq)ci+=`<div class="contact-line"><span>🐧</span>${tr(escapeHtml(contact.qq),15)}</div>`;if(contact.wechat)ci+=`<div class="contact-line"><span>💬</span>${tr(escapeHtml(contact.wechat),15)}</div>`;card.innerHTML=`<div class="person-name">${escapeHtml(t.name)}<span class="teacher-subject-tag">${sm[t.subject]||'👨‍🏫'} ${escapeHtml(t.subject||'')}</span></div><div class="person-contact">${ci}</div><div class="person-actions"><button class="btn btn-secondary btn-small" onclick="openFeedbackModal('${escapeHtml(t.name)}','teacher','evaluation')">评价</button><button class="btn btn-primary btn-small" onclick="openFeedbackModal('${escapeHtml(t.name)}','teacher','thanks')">感谢</button></div>`;ct.appendChild(card);}}catch(e){c.innerHTML='<div class="empty-state">加载失败</div>';}}

// ========== 同学录 ==========
async function renderClassmates(){document.getElementById('contentArea').innerHTML='<div class="global-search-box"><input type="text" id="classmateSearch" class="input" placeholder="搜索同学...（请等全加载完后再搜索否则会有BUG）" onkeyup="filterList(\'classmate\')"></div><div id="classmatesListContainer"></div>';renderClassmatesListInContainer();}
async function renderClassmatesListInContainer(){const ct=document.getElementById('classmatesListContainer');if(!ct)return;const others=allClassmates.filter(c=>c.name!==currentUser.name).sort((a,b)=>a.name.localeCompare(b.name,'zh-CN'));if(!others.length){ct.innerHTML='<div class="empty-state">暂无其他同学</div>';return;}ct.innerHTML='';for(const c of others){try{const contact=await(await fetch(`/contact/${encodeURIComponent(c.name)}`)).json();const card=document.createElement('div');card.className='person-card searchable-item';card.dataset.name=c.name;card.dataset.searchText=(c.name+' '+(contact.phone||'')+' '+(contact.qq||'')+' '+(contact.wechat||'')).toLowerCase();let ci='';if(contact.phone)ci+=`<div class="contact-line"><span>📱</span>${tr(escapeHtml(contact.phone),15)}</div>`;if(contact.qq)ci+=`<div class="contact-line"><span>🐧</span>${tr(escapeHtml(contact.qq),15)}</div>`;if(contact.wechat)ci+=`<div class="contact-line"><span>💬</span>${tr(escapeHtml(contact.wechat),15)}</div>`;card.innerHTML=`<div class="person-name">${escapeHtml(c.name)}</div><div class="person-contact">${ci}</div><div class="person-actions"><button class="btn btn-primary btn-small" onclick="openClassmateDetail('${escapeHtml(c.name)}')">查看</button></div>`;ct.appendChild(card);}catch(e){const card=document.createElement('div');card.className='person-card searchable-item';card.dataset.name=c.name;card.dataset.searchText=c.name.toLowerCase();card.innerHTML=`<div class="person-name">${escapeHtml(c.name)}</div><div class="person-contact"></div><div class="person-actions"><button class="btn btn-primary btn-small" onclick="openClassmateDetail('${escapeHtml(c.name)}')">查看</button></div>`;ct.appendChild(card);}}}

function filterList(type) {
  const kw = document.getElementById(type === 'teacher' ? 'teacherSearch' : 'classmateSearch')?.value.toLowerCase() || '';
  document.querySelectorAll('.searchable-item').forEach(card => {
    card.style.display = (card.dataset.searchText || '').includes(kw) ? 'grid' : 'none';
  });
}

function openMessageModal(toName){document.getElementById('modalTitle').textContent=`给 ${toName} 留言`;document.getElementById('modalBody').innerHTML='<textarea id="messageContent" class="input" rows="4" maxlength="500"></textarea>';document.getElementById('modalFooter').innerHTML=`<button class="btn btn-secondary" onclick="closeModal()">取消</button><button class="btn btn-primary" onclick="sendMessage('${escapeHtml(toName)}')">发送</button>`;document.getElementById('modal').classList.add('show');}
async function sendMessage(toName){const ct=document.getElementById('messageContent').value.trim();if(!ct){alert('请输入内容');return;}try{await fetch('/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({from_name:currentUser.name,to_name:toName,content:ct})});closeModal();alert('发送成功！');}catch(e){alert('发送失败');}}

// ========== 评价学生 ==========
function renderEvaluate(){const c=document.getElementById('contentArea');const st=allClassmates.filter(s=>s.name!==currentUser.name);if(!st.length){c.innerHTML='<div class="empty-state">暂无学生</div>';return;}c.innerHTML=`<div class="card"><div class="form-group"><label class="form-label">选择学生</label><select id="studentSelect" class="input">${st.map(s=>`<option value="${escapeHtml(s.name)}">${escapeHtml(s.name)}</option>`).join('')}</select></div><div class="form-group"><label class="form-label">评价</label><textarea id="evaluateContent" class="input" rows="4" maxlength="500"></textarea></div><button class="btn btn-primary" onclick="doEvaluate()">发表</button></div>`;}
async function doEvaluate(){const s=document.getElementById('studentSelect').value,ct=document.getElementById('evaluateContent').value.trim();if(!ct){alert('请输入内容');return;}try{await fetch('/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({from_name:currentUser.name,from_role:'teacher',to_name:s,to_role:'student',content:ct,type:'evaluation'})});alert('评价成功');switchTab('evaluate');}catch(e){alert('评价失败');}}

// ========== 感谢 ==========
async function renderThanks(){const c=document.getElementById('contentArea');try{const th=await(await fetch(`/feedback/${encodeURIComponent(currentUser.name)}?type=thanks`)).json();if(!th||!th.length){c.innerHTML='<div class="empty-state"><div class="empty-icon">🙏</div>还没有收到感谢</div>';return;}c.innerHTML=th.map(t=>`<div class="memory-card"><div class="memory-header"><span class="memory-from">${escapeHtml(t.from_name)}</span><span class="memory-time">${new Date(t.created_at).toLocaleString()}</span></div><div class="memory-content">${escapeHtml(t.content)}</div></div>`).join('');}catch(e){c.innerHTML='<div class="empty-state">加载失败</div>';}}

// ========== 管理员：所有留言 ==========
async function renderAllMessages(){const c=document.getElementById('contentArea');try{const data=await(await fetch(`/admin/all-data?requester=${encodeURIComponent(currentUser.name)}`)).json();let h='<div style="margin-bottom:16px;"><button class="btn btn-primary" onclick="openMessageAsModal()">✉️ 以他人名义发留言</button></div>';if(!data.messages||!data.messages.length)h+='<div class="empty-state">暂无留言</div>';else data.messages.forEach(m=>{h+=`<div class="memory-card message-card-admin"><button class="message-delete" onclick="deleteMessage(${m.id})">🗑️</button><div class="memory-header"><span class="memory-from">${escapeHtml(m.from_name)} → ${escapeHtml(m.to_name)}</span><span class="memory-time">${new Date(m.created_at).toLocaleString()}</span></div><div class="memory-content">${escapeHtml(m.content)}</div></div>`;});c.innerHTML=h;}catch(e){c.innerHTML='<div class="empty-state">加载失败</div>';}}
function openMessageAsModal(){const names=[...new Set([...allClassmates.map(c=>c.name),...allTeachers.map(t=>t.name)])];document.getElementById('modalTitle').textContent='以他人名义发留言';document.getElementById('modalBody').innerHTML=`<div class="form-group"><label class="form-label">发送者</label><select id="msgFrom" class="input">${names.map(n=>`<option value="${escapeHtml(n)}">${escapeHtml(n)}</option>`).join('')}</select></div><div class="form-group"><label class="form-label">接收者</label><select id="msgTo" class="input">${names.map(n=>`<option value="${escapeHtml(n)}">${escapeHtml(n)}</option>`).join('')}</select></div><div class="form-group"><label class="form-label">内容</label><textarea id="msgContent" class="input" rows="4" maxlength="500"></textarea></div>`;document.getElementById('modalFooter').innerHTML='<button class="btn btn-secondary" onclick="closeModal()">取消</button><button class="btn btn-primary" onclick="doMessageAs()">发送</button>';document.getElementById('modal').classList.add('show');}
async function doMessageAs(){const from=document.getElementById('msgFrom').value,to=document.getElementById('msgTo').value,ct=document.getElementById('msgContent').value.trim();if(!ct){alert('请输入内容');return;}try{await fetch('/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({from_name:from,to_name:to,content:ct,requester:currentUser.name})});closeModal();renderAllMessages();}catch(e){alert('发送失败');}}
async function deleteMessage(id){if(!confirm('确定删除？'))return;try{await fetch('/admin/delete-message',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({requester:currentUser.name,messageId:id})});renderAllMessages();}catch(e){alert('删除失败');}}

// ========== 管理员：所有人物 ==========
async function renderAllUsers(){const c=document.getElementById('contentArea');try{const data=await(await fetch(`/admin/all-data?requester=${encodeURIComponent(currentUser.name)}`)).json();let h=`<div style="margin-bottom:16px;"><button class="btn btn-primary" onclick="openAddUserModal()">➕ 添加用户</button></div><div class="stats-grid"><div class="stat-card"><div class="stat-value">${data.users.length}</div><div class="stat-label">总用户</div></div><div class="stat-card"><div class="stat-value">${data.messages.length}</div><div class="stat-label">留言</div></div><div class="stat-card"><div class="stat-value">${data.feedbacks.length}</div><div class="stat-label">评价</div></div><div class="stat-card"><div class="stat-value">${data.photos.length}</div><div class="stat-label">照片</div></div></div>`;data.users.forEach(u=>{const av=u.avatar||'😊',em=av.length<=2||!av.startsWith('http');h+=`<div class="card"><div class="card-header"><div class="card-avatar" style="border-radius:12px;">${em?av:`<img src="${escapeHtml(av)}" class="avatar-img">`}</div><div class="card-info"><div class="card-name">${escapeHtml(u.name)}<span class="role-tag ${u.role}">${u.role==='admin'?'管理员':(u.role==='teacher'?'老师':'同学')}</span></div></div><div class="admin-actions"><button class="btn-icon edit" onclick="openEditUserModal('${escapeHtml(u.name)}','${u.role}','${escapeHtml(u.phone||'')}','${escapeHtml(u.email||'')}','${escapeHtml(u.wechat||'')}','${escapeHtml(u.qq||'')}','${escapeHtml(u.subject||'')}')">编辑</button>${u.name!==currentUser.name?`<button class="btn-icon delete" onclick="deleteUser('${escapeHtml(u.name)}')">删除</button>`:''}</div></div><div class="card-detail">${u.phone?`<div class="card-detail-item"><span>📱</span>${escapeHtml(u.phone)}</div>`:''}${u.qq?`<div class="card-detail-item"><span>🐧</span>${escapeHtml(u.qq)}</div>`:''}${u.wechat?`<div class="card-detail-item"><span>💬</span>${escapeHtml(u.wechat)}</div>`:''}${u.email?`<div class="card-detail-item"><span>📧</span>${escapeHtml(u.email)}</div>`:''}</div></div>`;});c.innerHTML=h;}catch(e){c.innerHTML='<div class="empty-state">加载失败</div>';}}
function openAddUserModal(){document.getElementById('modalTitle').textContent='添加用户';document.getElementById('modalBody').innerHTML='<div class="form-group"><label class="form-label">姓名</label><input type="text" id="newUserName" class="input" maxlength="50"></div><div class="form-group"><label class="form-label">角色</label><select id="newUserRole" class="input"><option value="student">同学</option><option value="teacher">老师</option><option value="admin">管理员</option></select></div><div class="form-group"><label class="form-label">手机号</label><input type="tel" id="newUserPhone" class="input" maxlength="50"></div><div class="form-group"><label class="form-label">QQ</label><input type="text" id="newUserQQ" class="input" maxlength="20"></div><div class="form-group"><label class="form-label">邮箱</label><input type="email" id="newUserEmail" class="input" maxlength="100"></div><div class="form-group"><label class="form-label">微信</label><input type="text" id="newUserWechat" class="input" maxlength="50"></div><p style="font-size:13px;color:var(--gray-4);">默认密码：111111</p>';document.getElementById('modalFooter').innerHTML='<button class="btn btn-secondary" onclick="closeModal()">取消</button><button class="btn btn-primary" onclick="doAddUser()">添加</button>';document.getElementById('modal').classList.add('show');}
async function doAddUser(){const n=document.getElementById('newUserName').value.trim(),r=document.getElementById('newUserRole').value,ph=document.getElementById('newUserPhone').value.trim(),qq=document.getElementById('newUserQQ').value.trim(),em=document.getElementById('newUserEmail').value.trim(),wx=document.getElementById('newUserWechat').value.trim();if(!n){alert('请输入姓名');return;}try{const res=await(await fetch('/admin/add-user',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requester:currentUser.name,name:n,role:r,phone:ph,email:em,wechat:wx,qq})})).json();if(res.success){closeModal();renderAllUsers();loadClassmatesList();loadClassmates();}else alert(res.error);}catch(e){alert('添加失败');}}
function openEditUserModal(n,r,ph,em,wx,qq,sj){document.getElementById('modalTitle').textContent=`编辑 ${n}`;document.getElementById('modalBody').innerHTML=`<div class="form-group"><label class="form-label">角色</label><select id="editUserRole" class="input"><option value="student" ${r==='student'?'selected':''}>同学</option><option value="teacher" ${r==='teacher'?'selected':''}>老师</option><option value="admin" ${r==='admin'?'selected':''}>管理员</option></select></div>${r==='teacher'?`<div class="form-group"><label class="form-label">科目</label><input type="text" id="editUserSubject" class="input" value="${sj||''}" maxlength="20"></div>`:''}<div class="form-group"><label class="form-label">手机号</label><input type="tel" id="editUserPhone" class="input" value="${ph}" maxlength="50"></div><div class="form-group"><label class="form-label">QQ</label><input type="text" id="editUserQQ" class="input" value="${qq}" maxlength="20"></div><div class="form-group"><label class="form-label">邮箱</label><input type="email" id="editUserEmail" class="input" value="${em}" maxlength="100"></div><div class="form-group"><label class="form-label">微信</label><input type="text" id="editUserWechat" class="input" value="${wx}" maxlength="50"></div>`;document.getElementById('modalFooter').innerHTML=`<button class="btn btn-secondary" onclick="closeModal()">取消</button><button class="btn btn-primary" onclick="doEditUser('${escapeHtml(n)}')">保存</button>`;document.getElementById('modal').classList.add('show');}
async function doEditUser(n){const r=document.getElementById('editUserRole').value,ph=document.getElementById('editUserPhone').value.trim(),qq=document.getElementById('editUserQQ')?.value.trim()||'',em=document.getElementById('editUserEmail').value.trim(),wx=document.getElementById('editUserWechat').value.trim(),sj=document.getElementById('editUserSubject')?.value.trim()||'';try{const res=await(await fetch('/admin/update-user',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({requester:currentUser.name,targetName:n,role:r,phone:ph,email:em,wechat:wx,qq,subject:sj})})).json();if(res.success){closeModal();renderAllUsers();loadClassmatesList();loadClassmates();loadTeachers();}else alert(res.error);}catch(e){alert('保存失败');}}
async function deleteUser(name){if(!confirm(`确定删除 ${name} 吗？`))return;try{await fetch('/admin/delete-user',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({requester:currentUser.name,targetName:name})});renderAllUsers();loadClassmatesList();loadClassmates();loadTeachers();}catch(e){alert('删除失败');}}

// ========== 评价/感谢总览 ==========
async function renderAllFeedbacks(){const c=document.getElementById('contentArea');try{const data=await(await fetch(`/admin/all-data?requester=${encodeURIComponent(currentUser.name)}`)).json();if(!data.feedbacks||!data.feedbacks.length){c.innerHTML='<div class="empty-state">暂无评价或感谢</div>';return;}let h='<h4 style="margin-bottom:16px;">📊 所有评价与感谢</h4>';data.feedbacks.forEach(f=>{h+=`<div class="memory-card"><div class="memory-header"><span class="memory-from">${escapeHtml(f.from_name)} → ${escapeHtml(f.to_name)}</span><span class="memory-time">${new Date(f.created_at).toLocaleString()}</span></div><span class="role-tag ${f.type}">${f.type==='evaluation'?'📝 评价':'🙏 感谢'}</span><div class="memory-content">${escapeHtml(f.content)}</div></div>`;});c.innerHTML=h;}catch(e){c.innerHTML='<div class="empty-state">加载失败</div>';}}

// ========== 控制台 ==========
function renderConsole(){const c=document.getElementById('contentArea');const cmds=[{label:'所有用户',sql:'SELECT * FROM classmates'},{label:'最近20条留言',sql:'SELECT * FROM messages ORDER BY created_at DESC LIMIT 20'},{label:'最近20条评价',sql:'SELECT * FROM feedbacks ORDER BY created_at DESC LIMIT 20'},{label:'所有照片',sql:'SELECT * FROM photos'},{label:'所有歌曲',sql:'SELECT * FROM songs'},{label:'按角色统计',sql:"SELECT COUNT(*) as count, role FROM classmates GROUP BY role"},{label:'漂流瓶',sql:'SELECT * FROM drift_bottles ORDER BY created_at DESC'}];c.innerHTML=`<div class="card"><h4 style="margin-bottom:16px;">💻 SQL 查询</h4><textarea id="sqlInput" class="input" rows="4" placeholder="SELECT * FROM classmates LIMIT 5;"></textarea><button class="btn btn-primary" onclick="executeSQL()" style="margin-top:8px;">执行</button><div id="sqlResult" style="margin-top:16px;"></div></div><div class="card"><h4 style="margin-bottom:16px;">📋 快捷查询</h4><div class="cmd-list">${cmds.map(c=>`<div class="cmd-item" onclick="document.getElementById('sqlInput').value=\`${c.sql}\`;executeSQL()"><span>📋</span> ${c.label}</div>`).join('')}</div></div>`;}
async function executeSQL(){const sql=document.getElementById('sqlInput').value.trim(),rd=document.getElementById('sqlResult');if(!sql){rd.innerHTML='<div class="error">请输入 SQL</div>';return;}if(!sql.toUpperCase().startsWith('SELECT')){rd.innerHTML='<div class="error">仅允许 SELECT</div>';return;}rd.innerHTML='<div class="empty-state">查询中...</div>';try{const res=await(await fetch(`/admin/query?requester=${encodeURIComponent(currentUser.name)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sql})})).json();if(res.error){rd.innerHTML=`<div class="error">${escapeHtml(res.error)}</div>`;return;}if(!res.results||!res.results.length){rd.innerHTML='<div class="empty-state">无结果</div>';return;}const cols=Object.keys(res.results[0]);let h='<div style="overflow-x:auto;"><table class="result-table"><thead><tr>'+cols.map(c=>`<th>${escapeHtml(c)}</th>`).join('')+'</tr></thead><tbody>';res.results.forEach(r=>{h+='<tr>'+cols.map(c=>`<td>${escapeHtml(String(r[c]??''))}</td>`).join('')+'</tr>';});h+=`</tbody></table></div><p style="margin-top:8px;color:var(--gray-4);">共 ${res.results.length} 条</p>`;rd.innerHTML=h;}catch(e){rd.innerHTML='<div class="error">查询失败</div>';}}

// ========== 源码编辑器 ==========
async function renderEditor(){const c=document.getElementById('contentArea');c.innerHTML='<div class="empty-state">加载中...</div>';try{const res=await(await fetch(`/admin/list-files?requester=${encodeURIComponent(currentUser.name)}`)).json();if(res.error){c.innerHTML=`<div class="error">${res.error}</div>`;return;}const files=(res.files||[]).filter(f=>f.type==='blob'&&(f.path.endsWith('.js')||f.path.endsWith('.css')||f.path.endsWith('.html')||f.path.endsWith('.lrc')||f.path.endsWith('.txt')));let h='<h4 style="margin-bottom:16px;">📝 源代码</h4><div class="cmd-list">';files.forEach(f=>{h+=`<div class="cmd-item" onclick="openFileEditor('${f.path}')"><span>📄</span> ${f.path}</div>`;});h+='</div><div id="editorArea"></div>';c.innerHTML=h;}catch(e){c.innerHTML='<div class="empty-state">加载失败</div>';}}
async function openFileEditor(fp){const ea=document.getElementById('editorArea');ea.innerHTML='<div class="empty-state">加载中...</div>';try{const res=await(await fetch('/get-file',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filePath:fp})})).json();if(res.error){ea.innerHTML=`<div class="error">${res.error}</div>`;return;}const content=decodeURIComponent(escape(atob(res.content)));ea.innerHTML=`<div class="card"><h4>📄 ${fp}</h4><textarea id="editContent" class="input" rows="15" style="font-family:monospace;font-size:13px;">${escapeHtml(content)}</textarea><div style="display:flex;gap:8px;margin-top:12px;"><button class="btn btn-secondary" onclick="renderEditor()">取消</button><button class="btn btn-primary" onclick="saveFile('${fp}','${res.sha}')">💾 保存</button></div></div>`;}catch(e){ea.innerHTML='<div class="error">加载失败</div>';}}
async function saveFile(fp,sha){const content=document.getElementById('editContent').value;try{const res=await(await fetch('/admin/edit-file',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({requester:currentUser.name,filePath:fp,content,sha})})).json();if(res.success){alert('已保存');renderEditor();}else alert(res.error||'失败');}catch(e){alert('失败');}}

// ========== 签名墙 ==========
let sigCanvas,sigCtx,isDrawing=false,drawColor='#000000',drawSize=4,lastX=0,lastY=0;
async function renderSignature(){const c=document.getElementById('contentArea');c.innerHTML=`<div class="signature-toolbar"><label>颜色：</label><input type="color" id="drawColor" value="#000000" onchange="drawColor=this.value" style="width:36px;height:36px;border:none;border-radius:8px;"><label style="margin-left:8px;">粗细：</label><select id="drawSize" onchange="drawSize=parseInt(this.value)" style="padding:8px;border-radius:8px;border:1px solid var(--gray-2);"><option value="3">细</option><option value="6" selected>中</option><option value="10">粗</option><option value="16">特粗</option></select><button class="btn btn-small btn-outline" onclick="undoSignature()" style="margin-left:auto;">↩️</button><button class="btn btn-small btn-primary" onclick="openSignatureFullscreen()">🔲 全屏</button>${currentUser.role==='admin'?'<button class="btn btn-small btn-outline" onclick="clearSignature()" style="color:var(--danger);">🧹</button>':''}</div><div class="signature-container"><canvas id="signCanvas"></canvas></div><div style="margin-top:12px;"><button class="btn btn-primary" onclick="saveSignature()">💾 保存</button></div><div class="signature-fullscreen" id="sigFullscreen"><div class="fullscreen-toolbar"><label>颜色：</label><input type="color" id="fsDrawColor" value="#000000" onchange="drawColor=this.value;document.getElementById('drawColor').value=this.value" style="width:36px;height:36px;border:none;border-radius:8px;"><label style="margin-left:8px;">粗细：</label><select id="fsDrawSize" onchange="drawSize=parseInt(this.value);document.getElementById('drawSize').value=this.value" style="padding:8px;border-radius:8px;"><option value="3">细</option><option value="6" selected>中</option><option value="10">粗</option><option value="16">特粗</option></select><button class="btn btn-small btn-outline" onclick="undoSignature()" style="margin-left:auto;">↩️</button><button class="btn btn-small btn-primary" onclick="saveSignature()">💾</button><button class="btn btn-small btn-outline" onclick="closeSignatureFullscreen()">✕</button></div><canvas id="fsSignCanvas"></canvas></div>`;setTimeout(initSigCanvas,100);}
function initSigCanvas(){const cv=document.getElementById('signCanvas');if(!cv)return;sigCanvas=cv;sigCtx=cv.getContext('2d');cv.width=800;cv.height=600;fetch('/signature-wall').then(r=>r.json()).then(d=>{if(d.image_data){const img=new Image();img.onload=()=>sigCtx.drawImage(img,0,0,800,600);img.src=d.image_data;}else{sigCtx.fillStyle='#FFFFFF';sigCtx.fillRect(0,0,800,600);}});bindCanvasEvents(cv);}
function bindCanvasEvents(cv){cv.addEventListener('mousedown',e=>{isDrawing=true;const r=cv.getBoundingClientRect();lastX=(e.clientX-r.left)*(cv.width/r.width);lastY=(e.clientY-r.top)*(cv.height/r.height);});cv.addEventListener('mousemove',e=>{if(!isDrawing)return;const r=cv.getBoundingClientRect();const x=(e.clientX-r.left)*(cv.width/r.width);const y=(e.clientY-r.top)*(cv.height/r.height);sigCtx.beginPath();sigCtx.moveTo(lastX,lastY);sigCtx.lineTo(x,y);sigCtx.strokeStyle=drawColor;sigCtx.lineWidth=drawSize;sigCtx.lineCap='round';sigCtx.lineJoin='round';sigCtx.stroke();lastX=x;lastY=y;});cv.addEventListener('mouseup',()=>{isDrawing=false;});cv.addEventListener('mouseleave',()=>{isDrawing=false;});cv.addEventListener('touchstart',e=>{e.preventDefault();const t=e.touches[0];const r=cv.getBoundingClientRect();lastX=(t.clientX-r.left)*(cv.width/r.width);lastY=(t.clientY-r.top)*(cv.height/r.height);isDrawing=true;});cv.addEventListener('touchmove',e=>{e.preventDefault();if(!isDrawing)return;const t=e.touches[0];const r=cv.getBoundingClientRect();const x=(t.clientX-r.left)*(cv.width/r.width);const y=(t.clientY-r.top)*(cv.height/r.height);sigCtx.beginPath();sigCtx.moveTo(lastX,lastY);sigCtx.lineTo(x,y);sigCtx.strokeStyle=drawColor;sigCtx.lineWidth=drawSize;sigCtx.lineCap='round';sigCtx.lineJoin='round';sigCtx.stroke();lastX=x;lastY=y;});cv.addEventListener('touchend',()=>{isDrawing=false;});}
function openSignatureFullscreen(){const fs=document.getElementById('sigFullscreen');fs.classList.add('active');const fc=document.getElementById('fsSignCanvas');fc.width=800;fc.height=600;const scale=Math.min(window.innerWidth/800,window.innerHeight/600);fc.style.width=(800*scale)+'px';fc.style.height=(600*scale)+'px';fc.style.margin='auto';const fctx=fc.getContext('2d');const d=sigCanvas.toDataURL();const img=new Image();img.onload=()=>fctx.drawImage(img,0,0,800,600);img.src=d;bindCanvasEvents(fc);document.body.style.overflow='hidden';}
function closeSignatureFullscreen(){const fc=document.getElementById('fsSignCanvas');const d=fc.toDataURL();const img=new Image();img.onload=()=>{sigCtx.clearRect(0,0,800,600);sigCtx.drawImage(img,0,0,800,600);};img.src=d;document.getElementById('sigFullscreen').classList.remove('active');document.body.style.overflow='';}
function undoSignature(){const inFS=document.getElementById('sigFullscreen').classList.contains('active');const ctx=inFS?document.getElementById('fsSignCanvas').getContext('2d'):sigCtx;const cv=inFS?document.getElementById('fsSignCanvas'):sigCanvas;fetch('/signature-wall').then(r=>r.json()).then(d=>{ctx.fillStyle='#FFFFFF';ctx.fillRect(0,0,cv.width,cv.height);if(d.image_data){const img=new Image();img.onload=()=>ctx.drawImage(img,0,0,cv.width,cv.height);img.src=d.image_data;}});}
async function clearSignature(){if(!confirm('清除？'))return;try{await fetch('/signature-wall/clear',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({requester:currentUser.name})});sigCtx.fillStyle='#FFFFFF';sigCtx.fillRect(0,0,800,600);}catch(e){}}
async function saveSignature(){if(document.getElementById('sigFullscreen').classList.contains('active'))closeSignatureFullscreen();const d=sigCanvas.toDataURL('image/jpeg',0.85);try{const old=await(await fetch('/signature-wall')).json();let final=d;if(old.image_data){const mc=document.createElement('canvas');mc.width=800;mc.height=600;const mctx=mc.getContext('2d');const oi=new Image();await new Promise(r=>{oi.onload=r;oi.src=old.image_data;});mctx.drawImage(oi,0,0,800,600);const ni=new Image();await new Promise(r=>{ni.onload=r;ni.src=d;});mctx.drawImage(ni,0,0,800,600);final=mc.toDataURL('image/jpeg',0.85);}await fetch('/signature-wall',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image_data:final})});alert('已保存');}catch(e){alert('失败');}}

// ========== 歌单 ==========
async function renderSongs(){const c=document.getElementById('contentArea');try{const songs=await(await fetch('/songs')).json();let h='<div style="margin-bottom:16px;"><button class="btn btn-primary" onclick="openAddSongModal()">🎵 添加歌曲</button></div><h4 style="margin:16px 0 12px;">🎧 歌单</h4>';if(!songs||!songs.length){h+='<div class="empty-state"><div class="empty-icon">🎵</div>歌单为空</div>';}else{h+='<div class="song-list">';songs.forEach(s=>{h+=`<div class="song-item${currentSongName===s.name?' playing':''}" onclick="playSong('${escapeHtml(s.filename)}','${escapeHtml(s.name)}')"><div class="song-info"><span class="song-name">🎵 ${escapeHtml(s.name)}</span><span class="song-uploader">${escapeHtml(s.uploaded_by)}</span></div><span class="song-play">▶️</span></div>`;});h+='</div>';}c.innerHTML=h;}catch(e){c.innerHTML='<div class="empty-state">加载失败</div>';}}
function openAddSongModal(){document.getElementById('modalTitle').textContent='添加歌曲';document.getElementById('modalBody').innerHTML='<div class="form-group"><label class="form-label">歌曲名称</label><input type="text" id="songName" class="input" maxlength="100"></div><div class="form-group"><label class="form-label">MP3 和 LRC 文件</label><input type="file" id="songFiles" class="input" accept="audio/mpeg,.lrc" multiple></div><div id="songProgress" style="display:none;"><div class="progress-bar-bg"><div class="progress-bar-fill" id="songProgressFill"></div></div><p id="songProgressText" style="text-align:center;font-size:13px;color:var(--gray-4);margin-top:8px;">上传中...</p></div>';document.getElementById('modalFooter').innerHTML='<button class="btn btn-secondary" onclick="closeModal()">取消</button><button class="btn btn-primary" id="songUploadBtn" onclick="doAddSongWithFiles()">上传</button>';document.getElementById('modal').classList.add('show');}
async function doAddSongWithFiles(){const n=document.getElementById('songName').value.trim(),files=document.getElementById('songFiles').files;if(!n||!files||files.length===0){alert('请填写完整');return;}if(!/^[a-zA-Z0-9_\-\u4e00-\u9fa5]+$/.test(n)){alert('非法字符');return;}document.getElementById('songProgress').style.display='block';document.getElementById('songUploadBtn').disabled=true;try{const r=await uploadFilesToGitHub(Array.from(files),'songs',n);if(r.results){let ok=0;r.results.forEach(x=>{if(x.success)ok++;});document.getElementById('songProgressFill').style.width='100%';document.getElementById('songProgressText').textContent=`完成 ${ok}/${files.length}`;await fetch('/songs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:n,filename:n,uploaded_by:currentUser.name})});setTimeout(()=>{closeModal();renderSongs();},1000);}else{alert('失败');document.getElementById('songUploadBtn').disabled=false;}}catch(e){alert('失败');document.getElementById('songUploadBtn').disabled=false;}document.getElementById('songProgress').style.display='none';}
function playSong(folder,name){if(audio)audio.pause();currentSongName=name;audio=new Audio(`/songs/${folder}/${name}.mp3`);document.querySelector('.music-title').textContent=name;document.querySelector('.music-artist').textContent='歌单';fetch(`/songs/${folder}/${name}.lrc`).then(r=>{if(!r.ok)throw new Error('No lyrics');return r.text();}).then(t=>parseLRC(t)).catch(()=>{document.getElementById('lyricsContent').innerHTML='<div style="color:var(--gray-4);padding:20px;">暂无歌词</div>';});audio.addEventListener('timeupdate',updateProgress);audio.addEventListener('loadedmetadata',()=>{document.getElementById('duration').textContent=formatTime(audio.duration);});audio.addEventListener('play',()=>{document.querySelector('#playBtn svg').innerHTML='<path d="M6 19h4V5H6v14zm8-14v14h4V5h-4z"/>';document.getElementById('musicToggle').classList.add('playing');});audio.addEventListener('pause',()=>{document.querySelector('#playBtn svg').innerHTML='<path d="M8 5v14l11-7z"/>';document.getElementById('musicToggle').classList.remove('playing');});audio.addEventListener('ended',()=>{playNextSong();});audio.play().catch(()=>{});document.getElementById('musicPanel').classList.add('show');renderSongs();}

// ========== 个人资料 ==========
function renderProfile(){const c=document.getElementById('contentArea');const av=currentUser.avatar||'😊',em=av.length<=2||!av.startsWith('http');c.innerHTML=`<div class="card" style="text-align:center;"><div class="avatar-large" onclick="openAvatarModal()" style="border-radius:12px;">${em?av:`<img src="${escapeHtml(av)}" class="avatar-img">`}</div><div class="card-name" style="font-size:20px;justify-content:center;">${escapeHtml(currentUser.name)}</div><div style="color:var(--gray-4);margin-bottom:12px;">${currentUser.role==='admin'?'👑 管理员':(currentUser.role==='teacher'?'👨‍🏫 老师':'🎓 同学')}</div><button class="btn btn-outline btn-small" onclick="openAvatarModal()">更换头像</button></div><div class="card"><h4>📝 自我介绍</h4><textarea id="profileIntro" class="input" rows="3" maxlength="200"></textarea><button class="btn btn-primary" onclick="updateIntro()">保存</button><div id="introResult" class="result"></div></div><div class="card"><h4>💬 座右铭</h4><input type="text" id="profileMotto" class="input" maxlength="100"><button class="btn btn-primary" onclick="updateMotto()">保存</button><div id="mottoResult" class="result"></div></div><div class="card"><h4>📝 联系方式</h4><div class="form-group"><label class="form-label">手机号</label><input type="text" id="profilePhone" class="input" maxlength="100"></div><div class="form-group"><label class="form-label">QQ</label><input type="text" id="profileQQ" class="input" maxlength="20"></div><div class="form-group"><label class="form-label">邮箱</label><input type="email" id="profileEmail" class="input" maxlength="100"></div><div class="form-group"><label class="form-label">微信</label><input type="text" id="profileWechat" class="input" maxlength="50"></div><button class="btn btn-primary" onclick="updateProfile()">保存</button><div id="profileResult" class="result"></div></div><div class="card"><h4>🔐 修改密码</h4><div class="form-group"><label class="form-label">原密码</label><input type="password" id="oldPassword" class="input" maxlength="100"></div><div class="form-group"><label class="form-label">新密码</label><input type="password" id="newPassword" class="input" maxlength="100"></div><div class="form-group"><label class="form-label">确认密码</label><input type="password" id="confirmPassword" class="input" maxlength="100"></div><button class="btn btn-primary" onclick="changePassword()">修改</button><div id="passwordResult" class="result"></div></div><div class="card"><h4>🍾 漂流瓶</h4><p style="font-size:14px;color:var(--gray-5);margin-bottom:12px;">写信给未来的自己或他人</p><button class="btn btn-primary" onclick="openDriftBottleModal()">✉️ 投递</button><div style="display:flex;gap:8px;margin:12px 0;"><button class="btn btn-small btn-outline" id="btnSent" onclick="loadDriftBottles('sent')">我投递的</button><button class="btn btn-small btn-outline" id="btnInbox" onclick="loadDriftBottles('inbox')">我能打开的</button></div><div id="driftBottleList"></div></div>`;loadProfileContact();loadDriftBottles('sent');}
async function loadProfileContact(){try{const ct=await(await fetch(`/contact/${encodeURIComponent(currentUser.name)}`)).json();document.getElementById('profilePhone').value=ct.phone||'';document.getElementById('profileQQ').value=ct.qq||'';document.getElementById('profileEmail').value=ct.email||'';document.getElementById('profileWechat').value=ct.wechat||'';document.getElementById('profileMotto').value=ct.motto||'';document.getElementById('profileIntro').value=ct.intro||'';}catch(e){}}
async function updateIntro(){try{await fetch('/update-motto',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:currentUser.name,intro:document.getElementById('profileIntro').value.trim()})});document.getElementById('introResult').textContent='✅ 已保存';document.getElementById('introResult').style.color='var(--success)';}catch(e){}}
async function updateMotto(){try{await fetch('/update-motto',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:currentUser.name,motto:document.getElementById('profileMotto').value.trim()})});document.getElementById('mottoResult').textContent='✅ 已保存';document.getElementById('mottoResult').style.color='var(--success)';}catch(e){}}
async function updateProfile(){try{await fetch('/update-contact',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:currentUser.name,phone:document.getElementById('profilePhone').value,qq:document.getElementById('profileQQ').value,email:document.getElementById('profileEmail').value,wechat:document.getElementById('profileWechat').value})});document.getElementById('profileResult').textContent='✅ 已保存';}catch(e){}}
async function changePassword(){const old=document.getElementById('oldPassword').value,n=document.getElementById('newPassword').value,cf=document.getElementById('confirmPassword').value,r=document.getElementById('passwordResult');if(!old||!n||!cf){r.textContent='请填写完整';return;}if(n!==cf){r.textContent='两次不一致';return;}try{const res=await(await fetch('/change-password',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:currentUser.name,oldPassword:old,newPassword:n})})).json();r.textContent=res.success?'✅ 修改成功':res.error;r.style.color=res.success?'var(--success)':'var(--danger)';}catch(e){}}
function openAvatarModal(){document.getElementById('modalTitle').textContent='更换头像';document.getElementById('modalBody').innerHTML='<div class="form-group"><label>上传图片（会自动裁剪）</label><input type="file" id="avatarFile" class="input" accept="image/*"></div><canvas id="avatarCanvas" style="display:none;"></canvas><div id="avatarPreview" style="text-align:center;margin-top:12px;"></div><div id="avatarProgress" style="display:none;"><div class="progress-bar-bg"><div class="progress-bar-fill" id="avatarProgressFill"></div></div></div>';document.getElementById('modalFooter').innerHTML='<button class="btn btn-secondary" onclick="closeModal()">取消</button><button class="btn btn-primary" id="avatarSaveBtn" onclick="saveAvatar()">保存</button>';document.getElementById('modal').classList.add('show');window.selectedAvatar=null;
  const fileInput=document.getElementById('avatarFile');
  fileInput.addEventListener('change',function(){
    const file=this.files[0];if(!file)return;
    const canvas=document.getElementById('avatarCanvas');
    const ctx=canvas.getContext('2d');
    const img=new Image();
    img.onload=function(){
      const size=Math.min(img.width,img.height);
      const sx=(img.width-size)/2,sy=(img.height-size)/2;
      canvas.width=200;canvas.height=200;
      ctx.clearRect(0,0,200,200);
      ctx.beginPath();ctx.arc(100,100,100,0,Math.PI*2);ctx.clip();
      ctx.drawImage(img,sx,sy,size,size,0,0,200,200);
      document.getElementById('avatarPreview').innerHTML=`<img src="${canvas.toDataURL('image/jpeg',0.9)}" style="width:100px;height:100px;border-radius:50%;object-fit:cover;">`;
    };
    img.src=URL.createObjectURL(file);
  });
}
function selectAvatar(e){window.selectedAvatar=e;}
async function saveAvatar(){
  const canvas=document.getElementById('avatarCanvas');
  if(canvas.toDataURL().length>100){
    document.getElementById('avatarProgress').style.display='block';document.getElementById('avatarSaveBtn').disabled=true;
    const blob=await new Promise(r=>canvas.toBlob(r,'image/jpeg',0.9));
    const f=new File([blob],`${currentUser.name}.jpg`,{type:'image/jpeg'});
    try{const r=await uploadFilesToGitHub([f],'avatars');if(r.results&&r.results[0]&&r.results[0].success){const rawUrl=`/${r.results[0].path}`;await fetch('/update-avatar',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:currentUser.name,avatar:rawUrl})});currentUser.avatar=rawUrl;localStorage.setItem('currentUser',JSON.stringify(currentUser));closeModal();renderProfile();}else{alert('上传失败');}}catch(e){alert('上传失败');}
    document.getElementById('avatarProgress').style.display='none';document.getElementById('avatarSaveBtn').disabled=false;
  }else if(window.selectedAvatar){try{await fetch('/update-avatar',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:currentUser.name,avatar:window.selectedAvatar})});currentUser.avatar=window.selectedAvatar;localStorage.setItem('currentUser',JSON.stringify(currentUser));closeModal();renderProfile();}catch(e){}}
  else{alert('请选择图片');}
}

// ========== 漂流瓶 ==========
function openDriftBottleModal(){const names=[...new Set([...allClassmates.map(c=>c.name),...allTeachers.map(t=>t.name)])];document.getElementById('modalTitle').textContent='投递漂流瓶';document.getElementById('modalBody').innerHTML=`<div class="form-group"><label>收信人</label><select id="bottleTo" class="input"><option value="${escapeHtml(currentUser.name)}">给自己</option>${names.filter(n=>n!==currentUser.name).map(n=>`<option value="${escapeHtml(n)}">${escapeHtml(n)}</option>`).join('')}</select></div><div class="form-group"><label>打开时间</label><input type="datetime-local" id="bottleTime" class="input"></div><div class="form-group"><label>内容</label><textarea id="bottleContent" class="input" rows="4" maxlength="1000"></textarea></div>`;document.getElementById('modalFooter').innerHTML='<button class="btn btn-secondary" onclick="closeModal()">取消</button><button class="btn btn-primary" onclick="doSendDriftBottle()">投递</button>';document.getElementById('modal').classList.add('show');const tm=new Date();tm.setDate(tm.getDate()+1);document.getElementById('bottleTime').value=tm.toISOString().slice(0,16);}
async function doSendDriftBottle(){const to=document.getElementById('bottleTo').value,time=document.getElementById('bottleTime').value,ct=document.getElementById('bottleContent').value.trim();if(!time||!ct){alert('请填写完整');return;}try{await fetch('/drift-bottles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({from_name:currentUser.name,to_name:to,content:ct,open_time:time})});closeModal();alert('投递成功！');loadDriftBottles('sent');}catch(e){alert('投递失败');}}
async function loadDriftBottles(type){document.getElementById('btnSent').classList.toggle('active',type==='sent');document.getElementById('btnInbox').classList.toggle('active',type==='inbox');const list=document.getElementById('driftBottleList');try{const bottles=await(await fetch(`/drift-bottles/${type}?name=${encodeURIComponent(currentUser.name)}`)).json();if(!bottles||!bottles.length){list.innerHTML='<div class="empty-state">暂无漂流瓶</div>';return;}list.innerHTML=bottles.map(b=>{const canOpen=type==='inbox'||new Date(b.open_time)<=new Date();return`<div class="drift-bottle${!canOpen&&type==='sent'?' locked':''}"><div class="bottle-icon">${canOpen?'📬':'🔒'}</div><div class="bottle-from">${escapeHtml(b.from_name)} → ${escapeHtml(b.to_name)}</div><div class="bottle-time">打开：${new Date(b.open_time).toLocaleString()}</div>${canOpen?`<div class="bottle-content">${escapeHtml(b.content)}</div>`:'<div class="bottle-lock">🔒</div>'}</div>`;}).join('');}catch(e){list.innerHTML='<div class="empty-state">加载失败</div>';}}

// ========== 通用 ==========
function openFeedbackModal(toName,toRole,type){document.getElementById('modalTitle').textContent=type==='evaluation'?`评价 ${toName}`:`感谢 ${toName}`;document.getElementById('modalBody').innerHTML='<textarea id="feedbackContent" class="input" rows="4" maxlength="500"></textarea>';document.getElementById('modalFooter').innerHTML=`<button class="btn btn-secondary" onclick="closeModal()">取消</button><button class="btn btn-primary" onclick="doFeedback('${escapeHtml(toName)}','${toRole}','${type}')">发送</button>`;document.getElementById('modal').classList.add('show');}
async function doFeedback(toName,toRole,type){const ct=document.getElementById('feedbackContent').value.trim();if(!ct){alert('请输入内容');return;}try{await fetch('/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({from_name:currentUser.name,from_role:currentUser.role,to_name:toName,to_role:toRole,content:ct,type})});closeModal();alert('发送成功');}catch(e){alert('发送失败');}}
function closeModal(){document.getElementById('modal').classList.remove('show');}
function logout(){localStorage.removeItem('currentUser');currentUser=null;document.getElementById('mainPage').classList.remove('active');document.getElementById('loginPage').classList.add('active');document.getElementById('passwordInput').value='';document.getElementById('nameInput').value='';}

const savedUser=localStorage.getItem('currentUser');if(savedUser){currentUser=JSON.parse(savedUser);showMainPage();}loadClassmatesList();